(package "helafy"
         "0.1.0"
         "Minify/Uglify/Prettify contents")

(website-url "https://github.com/jcs-elpa/helafy")
(keywords "convenience")

(package-file "helafy.el")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
